FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y cowsay python3 python3-pip --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install pyjokes

CMD pyjoke | /usr/games/cowsay -f stegosaurus
